[project]
name = "spot-the-diff"
version = "0.1.0"
experiment_name = "Base"

[input_data]
raw_dir = 'data/raw'
split_dir = 'data/split'
batch_size = 32
num_workers = 4
image_size = [128,128]
seed = 1008


[model]
num_layers = 4
n_embd = 256
num_heads = 4
dropout = 0.1
dim_ratio = 4
patch_size = 16
max_sequence_length = 4

[training]
lr = 3e-4
max_steps = 4000
warmup_steps = 500
betas = [0.9, 0.95]
weight_decay = 0.1
gradient_clipping = 1.0
eval_interval = 500
log_interval = 500
scheduler = 'cosine'

[logging]
use_wandb = true
assets_dir = 'assets'
project_name= "spot-the-diff"
